app:
  name: mini_tiktok
  mode: dev
  
db:
  mysql:
    dsn: "mini_tiktok_user:mini_tiktok_pass@tcp(127.0.0.1:12000)/mini_tiktok?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    host: 127.0.0.1
    port: 6067
    db: 0
    username: ""
    password: ""
    auth: ""

registry:
  address:
    - 127.0.0.1:12004
  username: ""
  password: ""

jwt:
  signingkey: "mini_tiktok"