app:
  name: mini_tiktok
  mode: prod
  
db:
  mysql:
    dsn: "root:root@tcp(127.0.0.1:3306)/mini_tiktok?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    host: 127.0.0.1
    port: 6067
    db: 0
    username: ""
    password: ""

registry:
  address:
    - 127.0.0.1:2379
  username: ""
  password: ""