app:
  name: mini_tiktok
  mode: dev
  
db:
  mysql:
    dsn: "mini_tiktok_user:mini_tiktok_pass@tcp(127.0.0.1:12000)/mini_tiktok?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    address: "127.0.0.1:12003"
    password: "mini_tiktok_pass"
    id: 
      oss: 0
      favorite: 1
      relation: 2
      comment: 3

oss:
    endpoint: "ti.geektip.cc:12001"
    accesskey: "mini_tiktok_user"
    secretkey: "mini_tiktok_pass"
    videobucket: "video"
    imagebucket: "image"

registry:
  address:
    - 127.0.0.1:12004
  username: ""
  password: ""

jwt:
  signingkey: "mini_tiktok"

tracer:
  jaeger:
    host: "127.0.0.1"
    port: "12006"