app:
  name: mini_tiktok
  mode: prod
  
db:
  mysql:
    dsn: "root:root@tcp(127.0.0.1:3306)/mini_tiktok?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    address: "127.0.0.1:12003"
    password: "mini_tiktok_pass"
    db: 0

oss:
    endpoint: "127.0.0.1:12001"
    accesskey: "mini_tiktok_user"
    secretkey: "mini_tiktok_pass"
    videobucket: "video"
    imagebucket: "image"

registry:
  address:
    - 127.0.0.1:12004
  username: ""
  password: ""

jwt:
  signingkey: "mini_tiktok"