// Code generated by hertz generator.

package feed

import (
	"context"

	feed "github.com/HUST-MiniTiktok/mini_tiktok/cmd/api/biz/model/feed"
	"github.com/HUST-MiniTiktok/mini_tiktok/cmd/api/biz/rpc"
	"github.com/HUST-MiniTiktok/mini_tiktok/utils"
	"github.com/HUST-MiniTiktok/mini_tiktok/utils/conv"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/pkg/remote/trans/nphttp2/codes"
)

// GetFeed .
// @router /douyin/feed/ [GET]
func GetFeed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feed.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, util.NewRespMap(int32(codes.InvalidArgument), err.Error()))
		return
	}

	kitex_resp, err := rpc.FeedRPC.GetFeed(ctx, conv.ToKitexFeedRequest(&req))

	if err == nil {
		c.JSON(consts.StatusOK, conv.ToHertzFeedResponse(kitex_resp))
	} else {
		c.JSON(consts.StatusOK, util.NewRespMap(int32(codes.Internal), err.Error()))
	}
}
