// Code generated by hertz generator.

package feed

import (
	"context"

	feed "github.com/HUST-MiniTiktok/mini_tiktok/cmd/api/biz/model/feed"
	"github.com/HUST-MiniTiktok/mini_tiktok/cmd/api/biz/rpc"
	"github.com/HUST-MiniTiktok/mini_tiktok/pkg/errno"
	"github.com/HUST-MiniTiktok/mini_tiktok/pkg/utils/conv"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetFeed .
// @router /douyin/feed/ [GET]
func GetFeed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feed.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, conv.ToHertzBaseResponse(errno.ParamErr))
		return
	}

	kitex_resp, err := rpc.FeedRPC.GetFeed(ctx, conv.ToKitexFeedRequest(&req))

	if err == nil {
		c.JSON(consts.StatusOK, conv.ToHertzFeedResponse(kitex_resp))
	} else {
		c.JSON(consts.StatusOK, conv.ToHertzBaseResponse(err))
	}
}
